service: valuelist-ruby

env: flex
runtime: custom

resources:
  cpu: 8
  memory_gb: 10
  disk_size_gb: 20

automatic_scaling:
  min_num_instances: 3
  max_num_instances: 10
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.9
  target_concurrent_requests: 100

build_env_variables:
  APPLICATION_HOST: api.valuelist.cl
  DB_HOST: 34.95.207.155
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASSWORD: yZp63q3D6y
  DB_DATABASE: vl-production
  DATABASE_URL: "postgres://postgres:yZp63q3D6y@34.95.207.155:5432/vl-production"
  # REDIS_URL: redis://10.253.174.11:6379/1
  REDIS_URL: ecache-redis-cluster-1-valuelist.5xwue8.ng.0001.use1.cache.amazonaws.com:6379
  EMAIL_RECIPIENTS:
  SENDGRID_API_KEY: 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
  SENTRY_DSN:
  DEVISE_SECRET_KEY: C2D7CAC66861C68CA4EB513358831
  DEVISE_JWT_SECRET_KEY: 95C81D46FA61E95B7AB43F67E1484
  DEFAULT_EMAIL_ADDRESS: noreply@valuelist.cl
  SG_RESET_PASSWORD_TEMPLATE_ID: 3ef03857-3275-4f64-b312-5030fbb0485c
  CHANGE_PASSWORD_URL: /change-password
  S3_BUCKET: valuelist.cl
  AWS_ACCESS_KEY_ID: AKIAXSRWSHFEFXVSXDU7
  AWS_SECRET_ACCESS_KEY: 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
  AWS_REGION: us-east-2
  DEMO_EXPIRATION: 3600
  APIKEYS: "3D3783378F92DF1FFA4C6DD39AD5D,3972CC1DE3B84E9631493DDB247B4"
  ENV: development
  TEST_MAIL: test-emails-dev@valuelist.cl
  FRONT_BASE_URL: https://app.valuelist.cl
  AIRBRAKE_PROJECT_ID: 435832
  AIRBRAKE_PROJECT_KEY: 6b885f1b27935931a512531b4a18c379
  SECRET_KEY_BASE: b5c67d16ac294a7bc2275c55411a3bfb970c48bbd36f1e0955707496d65766b969d93e91ccfd00d786b39797e6fe428f4bfec15aaa98f58d928d792ffb5209fc
  SIDEKIQ_ADMIN_PASSWORD: 123456
  WEB_CONCURRENCY: 25
  MAX_THREADS: 25
  DB_POOL: 25
  RAILS_MAX_THREADS: 25
  RACK_TIMEOUT_SERVICE_TIMEOUT: 60
  UPDATE_CHARTS_COMPLEX_CRON: 0 2 * * *
  UPDATE_CHARTS_CRON: 0 4 * * *
  UPDATE_CHARTS_SIMPLE_CRON: 0 1 * * *
  GENERATE_AUM_CRON: 0 22 * * *
  JOB_UPDATE_DOLLAR: 0 0 * * *
  JOB_UPDATE_EURO: 0 0 * * *
  JOB_UPDATE_UF: 0 0 * * *

env_variables:
  APPLICATION_HOST: api.valuelist.cl
  DB_HOST: 34.95.207.155
  DB_PORT: 5432
  DB_USER: postgres
  DB_PASSWORD: yZp63q3D6y
  DB_DATABASE: vl-production
  DATABASE_URL: "postgres://postgres:yZp63q3D6y@34.95.207.155:5432/vl-production"
  # REDIS_URL: redis://10.253.174.11:6379/1
  REDIS_URL: ecache-redis-cluster-1-valuelist.5xwue8.ng.0001.use1.cache.amazonaws.com:6379
  EMAIL_RECIPIENTS:
  SENDGRID_API_KEY: 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
  SENTRY_DSN:
  DEVISE_SECRET_KEY: C2D7CAC66861C68CA4EB513358831
  DEVISE_JWT_SECRET_KEY: 95C81D46FA61E95B7AB43F67E1484
  DEFAULT_EMAIL_ADDRESS: noreply@valuelist.cl
  SG_RESET_PASSWORD_TEMPLATE_ID: 3ef03857-3275-4f64-b312-5030fbb0485c
  CHANGE_PASSWORD_URL: /change-password
  S3_BUCKET: valuelist.cl
  AWS_ACCESS_KEY_ID: AKIAXSRWSHFEFXVSXDU7
  AWS_SECRET_ACCESS_KEY: "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"
  AWS_REGION: us-east-2
  DEMO_EXPIRATION: 3600
  APIKEYS: "3D3783378F92DF1FFA4C6DD39AD5D,3972CC1DE3B84E9631493DDB247B4"
  ENV: development
  TEST_MAIL: test-emails-dev@valuelist.cl
  FRONT_BASE_URL: https://app.valuelist.cl
  AIRBRAKE_PROJECT_ID: 435832
  AIRBRAKE_PROJECT_KEY: 6b885f1b27935931a512531b4a18c379
  SECRET_KEY_BASE: b5c67d16ac294a7bc2275c55411a3bfb970c48bbd36f1e0955707496d65766b969d93e91ccfd00d786b39797e6fe428f4bfec15aaa98f58d928d792ffb5209fc
  SIDEKIQ_ADMIN_PASSWORD: 123456
  WEB_CONCURRENCY: 25
  MAX_THREADS: 25
  DB_POOL: 25
  RAILS_MAX_THREADS: 25
  RACK_TIMEOUT_SERVICE_TIMEOUT: 60
  UPDATE_CHARTS_COMPLEX_CRON: 0 2 * * *
  UPDATE_CHARTS_CRON: 0 4 * * *
  UPDATE_CHARTS_SIMPLE_CRON: 0 1 * * *
  GENERATE_AUM_CRON: 0 22 * * *
  JOB_UPDATE_DOLLAR: 0 0 * * *
  JOB_UPDATE_EURO: 0 0 * * *
  JOB_UPDATE_UF: 0 0 * * *
