image: atlassian/default-image:2

clone:
  depth: full
pipelines:
  branches:
    development:       
      - step:
          name: Build
          script: # mirror master to github
            - mv Procfile.elasticbean Procfile
            - git add .
            - git commit -m "Deploy development"
            - git archive HEAD --format=zip > deploy.zip
          artifacts: 
            - deploy.zip
      - step:
          name: "Deploy to Development"
          # Track production environments builds using deployments.
          deployment: development
          script:
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
            variables:
              AWS_ACCESS_KEY_ID: '$AWS_ACCESS_KEY_ID'
              AWS_SECRET_ACCESS_KEY: '$AWS_SECRET_ACCESS_KEY'
              AWS_DEFAULT_REGION: '$AWS_DEFAULT_REGION'
              APPLICATION_NAME: '$APPLICATION_NAME'
              ENVIRONMENT_NAME: '$ENVIRONMENT_NAME'
              S3_BUCKET: 'elasticbeanstalk-us-west-1-980156133571'
              VERSION_LABEL: DEV_${BITBUCKET_COMMIT:0:8}_$(date +%Y-%m-%d_%H%M%S)_$BITBUCKET_BUILD_NUMBER
              ZIP_FILE: 'deploy.zip'

    master:
      - step:
          name: Build
          script: # mirror master to github
            - mv Procfile.elasticbean Procfile
            - git add .
            - git commit -m "Deploy staging"
            - git archive HEAD --format=zip > deploy.zip
          artifacts: 
            - deploy.zip
      - step:
          name: "Deploy to Staging"
          # Track production environments builds using deployments.
          deployment: staging
          script:
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
            variables:
              AWS_ACCESS_KEY_ID: '$AWS_ACCESS_KEY_ID'
              AWS_SECRET_ACCESS_KEY: '$AWS_SECRET_ACCESS_KEY'
              AWS_DEFAULT_REGION: '$AWS_DEFAULT_REGION'
              APPLICATION_NAME: '$APPLICATION_NAME'
              ENVIRONMENT_NAME: '$ENVIRONMENT_NAME'
              S3_BUCKET: 'elasticbeanstalk-us-west-1-980156133571'
              VERSION_LABEL: STG_${BITBUCKET_COMMIT:0:8}_$(date +%Y-%m-%d_%H%M%S)_$BITBUCKET_BUILD_NUMBER
              ZIP_FILE: 'deploy.zip'

    prod:
      - step:
          name: Build
          script: # mirror master to github
            - mv Procfile.elasticbean Procfile
            - git add .
            - git commit -m "Deploy production"
            - git archive HEAD --format=zip > deploy.zip
          artifacts: 
            - deploy.zip
      - step:
          name: "Deploy to Production"
          # Track production environments builds using deployments.
          deployment: production
          script:
          - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
            variables:
              AWS_ACCESS_KEY_ID: '$AWS_ACCESS_KEY_ID'
              AWS_SECRET_ACCESS_KEY: '$AWS_SECRET_ACCESS_KEY'
              AWS_DEFAULT_REGION: '$AWS_DEFAULT_REGION'
              APPLICATION_NAME: '$APPLICATION_NAME'
              ENVIRONMENT_NAME: '$ENVIRONMENT_NAME'
              S3_BUCKET: 'elasticbeanstalk-sa-east-1-520879225160'
              VERSION_LABEL: PROD_${BITBUCKET_COMMIT:0:8}_$(date +%Y-%m-%d_%H%M%S)_$BITBUCKET_BUILD_NUMBER
              ZIP_FILE: 'deploy.zip'
