---
version: '3.4'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env.local
    environment:
      RAILS_ENV: development

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env.local
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

volumes:
  gem_cache:
  node_modules:
  # postgresql_data:
  # redis_data:
